### ISSUE TITLE
Mix of csv formats

### ISSUE THREAD

**Issue by vfisikop** [GeomScale/PorQua#8]
There are csv files that are comma separated e.g. https://github.com/GeomScale/GeoFin/blob/main/data/SPTR.csv but some of them are not e.g. https://github.com/GeomScale/GeoFin/blob/main/data/NDDLWI.csv

**Comment by Abhishek964170** [comment]
So basically what do you want , Can you please elaborate ?

**Comment by tejasathalye** [comment]
Hey @vfisikop , I have resolved the issue at #10 . Can you review the changes made?

**Comment by huuphuocle** [comment]
Hello, I think src/data_loader.py needs to be changed too, it's using `sep=';'` for MSCI data.
`df = pd.read_csv(os.path.join(path, 'msci_country_indices.csv'),
                        sep=';',
                        index_col=0,
                        header=0,
                        parse_dates=True)`
